name: Change Priority Label

on:
  issues:
    types: [labeled]

jobs:
  change_priority_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if label is P0 and was added more than 60 days ago
        id: check_label
        run: |
          label=$(jq -r ".label.name" $GITHUB_EVENT_PATH)
          if [ "$label" = "P0" ]; then
            added=$(jq -r ".label.created_at" $GITHUB_EVENT_PATH)
            days=$(( ( $(date -u +%s) - $(date -u +%s -d $added) ) / 86400 ))
            echo "::set-output name=days::$days"
          fi
        if: ${{ steps.check_label.outputs.days }} >= 1

      - name: Update Priority Label
        uses: actions/github-script@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;
            const labels = await github.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number
            });
            const currentLabel = labels.data.find(label => label.name === 'P0');
            if (currentLabel) {
              await github.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                name: currentLabel.name
              });
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                labels: ['P1']
              });
            }
